### ISSUE TITLE
re submission #1 checklist

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/phenology_dataset_study#41]
#### still to do
- [x] find home for "rules of thumb paragraph"
- [x] fix supp image absolute_scenario_rmse
- [x] write reviewer reply into paragraph

#### Sign off from co-authors
- [x] Joan
- [x] Kristina
- [x] Michael
- [x] Ethan

#### Manuscript upload checklist
- [x] main
- [x] reviewer reply
- [x] supp image
- [x] supp methods
- [x] main text diff pdf

#### Misc
- [x] update all images on github
- [ ] upload new zenodo version
- [ ] upload new bioarxiv version (main, & 2 supplements)

**Comment by sdtaylor** [comment]
doooooooone
