### ISSUE TITLE
final submission formatting/logistics checklist

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/phenology_dataset_study#43]
## Specific things called for by review specialist

- [x]  Please provide the main text/tables in Word or PDF+LaTeX format.  Word is preferred.  See Item 1 in the Checklist for Authors below.

- [x]  Rather than rotating the bodies of Tables 1 and 2 to read from bottom-to-top, the page layouts should instead be rotated from portrait to landscape view, with the tables set reading left-to-right.  The same applies for figure images (Figs. 1, 3, and 4).

- [x]  Present the Figure Legends together as a group, on the pages following the last table and preceding the first figure.

- [x]  Replace the current version of Fig. 1 with a higher resolution version suitable for publication.

- [x]  Figs. 2, 3, and 4 will need sizing/layout adjustments to meet the page requirements. Please provide these figures sized for PDF publication, with each entire image sized no larger than portrait layout (maximum 6 inches wide x 8 inches high) or landscape layout (maximum 8.75 inches wide x 5.25 inches high). All text must be sized between 6 and 10 point when the image is sized for publication.  For readability, we suggest using a text size hierarchy, sizing axis numbers between 6-7 point, axis labels between 8-9 point, panel labels that consist of words between 7-8 point, and panel labels that consist of a single letter at 10 point.

- [x]  Relabel the Supplementary Methods as Appendix S1 (including the title at the top of the document, the name of the file itself, and references to the material).

- [x]  Relabel the Supplementary Figures/Tables file as Appendix S2 (again, including the title at the top of the document, the name of the file itself, and references to the material).

- [x]  Prepare Appendices S1 and S2 in the format intended for publication.  Note this material is not copy edited or typeset.  Please check it carefully; I see the initial word is missing from the manuscript title given at the of both files and that in some cases page numbering (page 5 of Appendix S2, for example).

- [x]  In the Data Archiving section of the online submission form you've indicated that all code, original data, and derived data will be posted on Zenodo. Although data archiving is not a requirement of this journal, if you are planning to archive data it should be completed at this stage because the production process moves quickly. If archiving data with GitHub/Zenodo, please do so at this time and update this section of the online form to provide the Zenodo DOI assigned to the data deposit. If you choose not to archive data at this time, please update the form to indicate this.

**Comment by sdtaylor** [comment]
## Generic checklist

CHECKLIST FOR AUTHORS
How to Prepare Your Accepted Manuscript for Publication

- [x]  Upload the main manuscript file and tables in Word or LaTeX. If your manuscript was prepared in LaTeX, please upload a ZIP of the LaTeX source files and include a PDF version.

- [x] Assemble the parts of the manuscript in the following order: Title page, Abstract, Key words, Text, Acknowledgments, Literature Citations, Tables (table legend, headings, data, footnotes), Figure Legends, Figures.

- [x] Completely double space all text in the manuscript, including table legends and footnotes. All pages should have 1 inch margins on all sides.

- [x] Prepare the manuscript using Times New Roman font in a 12-point size. Number the pages sequentially, beginning with the title page.

- [x] Check that the hierarchy of text headings is discernible.

- [x] Confirm that tables and figures are mentioned in the body of the manuscript in numeric order.

- [x] For Word submissions, tables must be provided in an editable format as true tables in the Word file, created using the "Insert Table" function, rather than using tabs, spaces, or embedded images. Tables cannot contain colors, shading or graphics. If such enhancements are needed, the information must be presented as a figure.

- [x] Provide each figure a single time, as a high-resolution image suitable for publication. Preferred file formats include TIF, EPS, PDF, or AI created using at least 600 dpi, while JPEG, PPT/PPTX, or DOC/DOCX are also acceptable if the resolution is sufficient. See Author Guidelines for more details. Ultimately we are looking for files that not only create crisp, clean prints, but also remain crisp and clear when the on-screen view is significantly zoomed in.

- [x] Prepare and submit any previously provided Supporting Information for online publication in Wiley Online Library. New material cannot be added at this stage. Supporting Information is not edited or typeset, and thus should be supplied in the format intended for posting online. For materials prepared in LaTeX, please supply a PDF only. Each appendix must be provided in a separate file. To avoid publication delays please review the naming conventions for this material and the file naming requirements prior to submission: https://esajournals.onlinelibrary.wiley.com/hub/journal/19399170/resources/author-guidelines-ecy#Supporting_Information

- [ ] If authors wish to embargo the paper for release on a specific date to coordinate a press release, this request must be made in the "Press Release" section of the online submission form when submitting your final version.  General information on ESA’s publicity and embargo policies can be found online: https://esajournals.onlinelibrary.wiley.com/hub/journal/19399170/resources/publicity-esa

**Comment by sdtaylor** [comment]
maybe put together a better figure 2. 

done https://github.com/sdtaylor/phenology_dataset_study/commit/8b08589f5043eebb9fbdf4655a4daf2961cae168

**Comment by sdtaylor** [comment]
boom https://doi.org/10.1002/ecy.2568
